---
- name: Precoonfig
  hosts: yoriqulov
  tasks:
    - name: Install docker
      block:
        - name: Installing additional packages
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update_cache: yes
            cache_valid_time: 86400

        - name: Add docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Set up repo
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
            state: present
            update_cache: yes
            filename: docker

        - name: Install docker-ce
          apt:
            name: docker-ce
            update_cache: yes

        - name: Check docker installed and restarted
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: Install docker-compose
      block:
        - name: Get latest version of docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: Installing docker-compose
          get_url:
            url: https://github.com/docker/compose/releases/download/{{page.json.tag_name}}/docker-compose-linux-x86_64
            dest: ~/.docker/cli-plugins/docker-compose
            mode: 0755
      become: yes

    - name: Finish installation
      block:
        - name: Add user to docker group
          user:
            name: "{{ansible_user}}"
            groups: docker
            append: yes

        - name: Reboot
          reboot:
      become: yes
