version: "3.8"
services:
  api:
    extends:
      file: docker-compose.api.yml
      service: api
    depends_on:
      - rmq
  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - myNetwork
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      - converter
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    container_name: app
    restart: always
    networks:
      - myNetwork
    env_file:
      - ./apps/app/.env
    ports:
      - "3001:80"
    expose:
      - "80"
    depends_on:
      - api
  converter:
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    container_name: converter
    restart: always
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
