---
- name: user
  hosts: yoriqulov
  tasks:
    - name: Create user
      vars:
        user: yoriqulov
      user:
        name: "{{user}}"
        state: present
      become: true
      register: response
    - debug:
        var: response
