---
- name: user
  hosts: yoriqulov
  tasks:
    - name: Preconfig block
      block:
        - name: Create user
          vars:
            user: yoriqulov
          user:
            name: "{{user}}"
            state: present
          register: error
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: error
      become: true
      rescue:
        - name: ERROR WAS HERE
          debug:
            var: error
      always:
         - name: Reboot
           debug:
             msg: 'Rebooooooting'
