---
- name: user
  hosts: yoriqulov
  tasks:
    - name: Preconfig block
      block:
        - name: Sleep
          command: /bin/sleep 15
          async: 1000
          poll: 5
      become: true
