---
- name: user
  hosts: yoriqulov
  tasks:
    - name: Preconfig block
      block:
        - name: Create user
          vars:
            user: yoriqulov
          user:
            name: "{{user}}"
            state: present
          register: response
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: response
      become: true
    - debug:
        var: response
